### ISSUE TITLE
PGConverter won't convert from PRIDE xml to mzTab

### ISSUE THREAD

**Issue by davidserv** [PRIDE-Toolsuite/PGConverter#3]

**Comment by davidserv** [comment]
Hi,

I operate on CentOS 6.9 64bit with Java 1.8.

When I launch pgconverter this way "java -jar pg-converter-1.3/pg-converter.jar -c -pridexml Pride.pride.xml -outputformat mztab" I get:

INFO  MainApp - Starting application...
INFO  MainApp - Program arguments: [-c, -pridexml, Pride.pride.xml, -outputformat, mztab]
INFO  Converter - Starting conversion...
INFO  Utility - Exiting application.

No output file is created. When I check whether my PRIDE xml is valid, pgconverter says it is valid with no problem. What is wrong with the conversion function in pgconverter ?

David S.

**Comment by Tobias-Ternent** [comment]
Hi David, thanks for getting in touch. I think you're doing everything right, and it looks like I've recently introduced a bug that the unit tests weren't catching. I'll aim to take a look at this tomorrow to make some improvements, and hopefully I'll be able to get back to you soon.
Tobias

**Comment by davidserv** [comment]
Gald to hear that, thanks for helping me :)

David S.

**Comment by Tobias-Ternent** [comment]
Hi @davidserv, I believe I have fixed the problem now. I have made a new version of this tool now, please can you download it from here and try again?
https://drive.google.com/open?id=0ByPwkIg-BdVzSGEwanVuc1hDdUE
Tobias

**Comment by davidserv** [comment]
I confirm the pgconverter works like a charm now, it performs the conversion with no flaw. Thank you very much Tobias, I appreciate the quick help !

David S.
